### ISSUE TITLE
Switch to sparse matrices

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#13]
@kkloste's calculations suggest that our large matrices are sparse.

Switching to a sparse encoding could reduce the Gene by Biological Process matrix from ~1000 MB in RAM to ~15 MB in RAM.

**Comment by kkloste** [comment]
I just tried running our diffusion-example.ipynb notebook on my laptop and it ran out of memory in our diffuse_along_metapath() function, because of these dense matrices.
Further evidence we should look into using sparse matrices.

```
---> 45     adjacency_matrix = numpy.zeros((len(target_node_to_position), len(source_nodes)))
     46     for j, source_node in enumerate(source_nodes):
     47         for edge in source_node.edges[metaedge]:

MemoryError: 
```

**Comment by dhimmel** [comment]
@kkloste how do you choose which [sparse matrix format](https://docs.scipy.org/doc/scipy-0.18.1/reference/sparse.html) to use?

**Comment by kkloste** [comment]
Depends on what kinds of operation(s) account for the bulk of the work you'll perform with the matrix.
We are doing mostly mat-vecs and matrix multiplies, so CSC and CSR offer the most compact storage and most efficient operations. In contrast, if we were instead going to be doing a lot of querying individual edges, then DOK or COO would be more efficient.

I recommend CSC. CSC and CSR offer effectively the same kind of advantages, but our operations (matrix times column vector) should be more efficient in CSC (a column-oriented storage scheme).

**Comment by kkloste** [comment]
I should clarify:

the matrices that we perform the multplications with would be best stored as CSC.
BUT, converting to CSC takes a non-trivial amount of resources -- the gain we get from speeding up multiplications by using sparse matrices is lost if we have to convert a new matrix to CSC each time we perform a multiplication.

That said, if we expect that we can cache a CSC matrix and use it multiple times in the future, the conversion can be worth it if we re-use enough.

**Comment by kkloste** [comment]
The sparse matrix format for the larger hetnet object, I am not sure about.
I have to better understand all the different kinds of data it's holding.
 We should set up a quick skype meeting to discuss this.

**Comment by kkloste** [comment]
It seems that multiplying a numpy dense matrix by a sparse matrix will yield a dense matrix if performed this way:

https://docs.scipy.org/doc/scipy/reference/sparse.html

This means we could store all the hetionet inputs (the matrices encoding each different type of meta edge) as sparse matrices (so it doesn't cost us as much memory to cache them), but still use a dense matrix for the iterative solution (which we want to do  because the solution is often dense).

**Comment by dhimmel** [comment]
@kkloste from the [scipy.sparse docs](https://docs.scipy.org/doc/scipy/reference/sparse.html):

> As of NumPy 1.7, np.dot is not aware of sparse matrices, therefore using it will result on unexpected results or errors.

So that makes me think that `scipy_sparse_matrix.dot(numpy_ndarray)` will work but `numpy_ndarray.dot(scipy_sparse_matrix)` will not work.

Currently, we're using the [PEP 465](http://legacy.python.org/dev/peps/pep-0465/) `@` notation for matrix dot products. I saw @jakevdp added support for `@` to scipy in https://github.com/scipy/scipy/pull/5347 (from 2015!).

@jakevdp do you happen to know whether both of the following will work:

1. `scipy_sparse_matrix @ numpy_ndarray`
2. `numpy_ndarray @ scipy_sparse_matrix`

Or will only option 1 work, as the object that's listed first determines the function that gets called?

@kkloste (@jakevdp no need to worry about this next part): if only option 1 works, that's a reason to hold off on implementing #27, as having the sparse input matrix come first is actually a workaround...

**Comment by jakevdp** [comment]
both should work, as long as the array is not a scalar. 2 will trigger ``sparse.__rmatmul__``

**Comment by dhimmel** [comment]
> both should work, as long as the array is not a scalar. 2 will trigger `sparse.__rmatmul__`

Confirmed @jakevdp's statement in [this notebook](https://github.com/dhimmel/hetmech/blob/matmul/4.scipy-matmul.ipynb). Both orders work with the `@` operator. However, if using `.dot`, only `scipy_sparse_matrix.dot(numpy_ndarray)` works.

This is a huge reason to use the `@` operator whenever possible, especially when you know the input will be matrix-like, but you want flexibility on which types of matrix objects are supported!

**Comment by dhimmel** [comment]
@zietzm let's have you look into using sparse matrices in `diffusion.diffuse` and `degree_weight.dwwc`. 

The larger question is if we switch to sparse adjacency matrices in those functions, which intermediate variables stay dense and which become sparse.

Is there a cutoff (e.g. 60% nonzero) where we want to revert back to dense matrices? And of course, which sparse matrix format to use.

This is a large task, so feel free to address it in multiple pull requests or open new issues for the subtopics.

**Comment by kkloste** [comment]
The cutoff for when it is beneficial to use a sparse format instead of a dense format will depend on the matrix size (not just the % nonzeros) as well as a given machine's architecture.

A useful general-purpose cut-off for when sparse storage is beneficial memory-wise is `nnz < (n^2)/3`, so less than 33%.

**Comment by dhimmel** [comment]
> A useful general-purpose cut-off for when sparse storage is beneficial memory-wise is `nnz < (n^2)/3`, so less than 33%.

What is `n`? Number of elements, i.e. `numpy.prod(matrix.shape)`?

**Comment by kkloste** [comment]
Here `n` is the dimension of the (presumed square) matrix and `nnz` is the number of nonzeros in it.

A more flexible way to write this is ` nnz < (1/3)*"product of the dimensions of the matrix"`

**Comment by zietzm** [comment]
@dhimmel @kkloste 

I created arrays with 100,000,000 elements of varying sparsity and looked at the computation time doing [`dwwc_step`](https://github.com/greenelab/hetmech/blob/master/hetmech/degree_weight.py#L6-L42) and [`diffusion_step`](https://github.com/greenelab/hetmech/blob/master/hetmech/diffusion.py#L10-L54). 

<img src="https://user-images.githubusercontent.com/7230303/27198924-2786f3aa-51e2-11e7-9a85-27fa34782c16.png" width="400">

Every data point here is the average of dwwc_step and diffusion_step (each over rows and then over columns `damping=0.5`). The four individual values (which were averaged) were roughly the same for all of these.

Then I looked at the memory usage for these arrays (not in computation, just by themselves). Note the scale of the y-axis. (1.5 means 150 MB)

<img src="https://user-images.githubusercontent.com/7230303/27199500-3de08704-51e4-11e7-9927-406ddc1ceb63.png" width="400">

So on my machine, the sparse matrix started taking up more memory around 20% sparsity. Throughout both, the computation time was faster for sparse matrices though. I would be interested to see the performance of this on other machines.

Not sure what this means for hetmech, if we should switch to dense at 20% nnz or if the faster computation time should win out, etc. 

Hopefully this info could be helpful in the future.

**Comment by kkloste** [comment]
Very cool, @zietzm !

The answer to your question depends on what computation is being performed, I think:
if we're multiplying together giant subsections of the full hetmech matrix, then memory is the priority (because otherwise in some cases you run out of memory) and we should use whichever format (dense/sparse) uses less memory.

For smaller computations where the size of the matrices is small enough that memory isn't a concern, we can prioritize speed. That said, it should be noted that converting a matrix from dense/sparse to sparse/dense has its own cost, and we don't want to be performing those conversions repeatedly, either.

My first thoughts are that we should keep everything sparse (for the speedup and memory efficiency)
but for any computation that might involve matrices with large enough size and nnz to cause memory issues, we convert back to dense on an ad-hoc basis.
