### ISSUE TITLE
Alternatives to XSwap for hetnet permutation

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#134]
We had a hetmech conference call today with @bdsullivan @cgreene @zietzm @kkloste and Drew van der Poel. @bdsullivan brought up the possibilities of using other methods than XSwap to create permuted hetnets. In the past, we've discussed implementations of XSwap in https://github.com/greenelab/hetmech/issues/46 but have not evaluated completed different methods of generating permuted networks.

Here is the description of our current method from the [Project Rephetio](https://doi.org/10.7554/eLife.26726) manuscript:

> From Hetionet, we derived five permuted hetnets ([Himmelstein, 2016b](https://doi.org/10.15363/thinklab.d178)). The permutations preserve node degree but eliminate edge specificity by employing an algorithm called XSwap to randomly swap edges ([Hanhijärvi et al., 2009](https://doi.org/10.1137/1.9781611972795.67)). To extend XSwap to hetnets ([Himmelstein and Baranzini, 2015a](https://doi.org/10.1371/journal.pcbi.1004259)), we permuted each metaedge separately, so that edges were only swapped with other edges of the same type. We adopted a Markov chain approach, whereby the first permuted hetnet was generated from Hetionet v1.0, the second permuted hetnet was generated from the first, and so on. For each metaedge, we assessed the percent of edges unchanged as the algorithm progressed to ensure that a sufficient number of swaps had been performed to randomize the network ([Himmelstein, 2016b](https://doi.org/10.15363/thinklab.d178)). Permuted hetnets are useful for computing the baseline performance of meaningless edges while preserving node degree ([Himmelstein, 2015l](https://doi.org/10.15363/thinklab.d136)).

Currently, our HetMat data structure has a [function](https://github.com/greenelab/hetmech/blob/d4d1e2918e9538ac9dc1689e4636c4c1998f2f47/hetmech/hetmat/__init__.py#L237-L256) for generating permuted hetnets using XSwap, which delegates to [`hetmech.matrix.permute_matrix`](https://github.com/greenelab/hetmech/blob/d4d1e2918e9538ac9dc1689e4636c4c1998f2f47/hetmech/matrix.py#L84-L106), which delegates to [`hetio.permute.permute_pair_list`](https://github.com/dhimmel/hetio/blob/f2e525a1306f398f839e5410d190d750e173365b/hetio/permute.py#L49-L145). We've now generated 200 permuted hetnets derived from Hetionet v1.0.

@bdsullivan mentioned some other methods for generating permuted graphs. My notes include random-graph model, configuration model, and Chung Lu. So if anyone wants to suggest an alternative and how it would differ in terms of output from XSwap, that would be a good starting point.

**Comment by bdsullivan** [comment]
(below is copied over from Slack) 
@kkloste  [10:00 AM, July 26]
@dhimmel -- it was my impression from our conversation that the "permuted networks" that you make are not simply graphs with a specified degree sequence, but have a bit more structure.
More specifically, it seems like (to use a simplified example) the graph has several partitions ( A, B and C, say), and you want the permuted network to have the same number of nodes in each partition, as well as the same "between-partition-degree".

To clarify: if node v in A has 3 neighbors in A, 5 neighbors in B, and 7 neighbors in C,
is it the case that you want every permuted network to have node v with 3 neighbors in A, 5 in B, 7 in C?

If yes, then the vanilla configuration model is not what we want here.

@dhimmel  [10:49 AM]
@kkloste  for a given metaedge (type of edge), the edge swaps are performed without any sort of partitioning to retain community structure. Each metaedge is permuted separately and when we refer to degree, we mean degree for a specific metaedge. As such, to create a permuted hetnet, we are actually calling `permute_pair_list` 24 times (once for each metaedge).

**Comment by kkloste** [comment]
Ok, I think I'm starting to understand, @dhimmel .
But I want to make sure I get what `permute_pair_list` is doing.
Can you correct me if this understanding is wrong?

You start by specifying a particular metaedge, e.g. "A to B".

"Permuting the metaedge" means that we look at all the actual edges in "A to B", and for each edge, potentially swap its endpoints with those of other edges.

"Preserving degree" then means that when you permute within metaedge "A to B", each node v in A should have the same number of neighbors in B when the shuffling is done (compared with the number of neighbors v had in B prior to shuffling). And the same is true of each node in B.

Is this accurat @dhimmel ?

**Comment by dhimmel** [comment]
> I want to make sure I get what `permute_pair_list` is doing.

Might as well kill :bird: :bird: with one :gem:, so I opened https://github.com/hetio/hetio/pull/24 to add docstrings to the `hetio.permute` functions. @kkloste would be happy if you reviewed that PR.

> "Preserving degree" then means that when you permute within metaedge "A to B", each node v in A should have the same number of neighbors in B when the shuffling is done (compared with the number of neighbors v had in B prior to shuffling). And the same is true of each node in B.

Yes. There is an extra qualification that must be added however. The edge swaps are performed separately for each metaedge. Hence, you could have a situation where there are two types of edges between metanode A and metanode B. Let's assume there is AxB and AyB where x and y are different edge types. In this case, each A or B node has an x degree and a y degree. Both of these degrees are preserved, because edge sets of different types are swapped completely independently.

> "Permuting the metaedge" means that we look at all the actual edges in "A to B", and for each edge, potentially swap its endpoints with those of other edges.

Applying the same qualification as above, then yes. The algorithm proceeds by randomly picking two edges (of the same type) and attempting a swap. Sometimes a swap is invalid (for example it could result in an existing edge) and hence is skipped. This process occurs iteratively many times where two edges are selected and a swap of the endpoints is attempted.

**Comment by kkloste** [comment]
Thanks for the clarifications @dhimmel , this helps immensely!
Happy to review the PR.

**Comment by kkloste** [comment]
@dhimmel 
Ok, finally had the chance to finish my analysis of the Xswap algorithm, regarding how well the procedure samples uniformly at random from the space of graphs that match our desired structure.

One complication is that we want a specific, fixed degree sequence (not an expected degree distribution like the Erdos-Renyi or Chung-Lu models), and that makes it a bit difficult to see what "the space of graphs matching our desired structure" looks like.

Say we are looking at just meta-edge "A to B", so our graph is essentially bipartite (A nodes and B nodes), and each node has a specified target degree value, i.e. u in A must have degree d(u).
Let m be the total number of edges, and note that since this graph is bipartite we have

m = sum_{u in A} d(u) = sum_{b in B} d(v)

A Chung-Lu model of this graph would assign each edge (u,v) the probability

P(u,v) = d(u)*d(v)/m.

In contrast, with the Xswap procedure, if carried out an arbitrarily large number of times, the probability of edge (u,v) being present approaches

P(u,v) = d(u)*d(v)/( m + d(u)*d(v) - d(u)-d(v)+1 )

which is slightly less than for Chung-Lu.

I don't want to say this means "Xswap is wrong" though, because I believe we're sampling from different graph spaces.

My point is -- it's really unclear to me how to reason about "sampling uniformly at random from the distribution of graphs with the exact specified degree sequence" --- I don't think it's possible to count the number of graphs in that space (in a simple, closed formula kind of way).

But I *also* don't know that this is really the space of graphs we want to be sampling from --- since data is incomplete and has errors, do we want to enforce this exact degree sequence? Or just a degree *distribution* that has this degree sequence as its expected outcome?

The good news is if we switch to a Chung-Lu style sampling, then we can compute the "null distribution" values deterministically, without any xswap procedure, for all metapaths, in a pretty straight-forward manner.

**Comment by dhimmel** [comment]
# Analytically deriving the probability that an edge exists in a permuted network

Thanks @kkloste for your investigation. In this comment I want to address the probability of an edge existing in a permuted network. I'll address everything else in another comment.

Specifically, in Project Rephetio and @danich1's current edge prediction work, it is helpful to know the "prior probability" of an edge, which we define as the probability it exists in an XSwap-derived permutation. In Project Rephetio, we wanted to estimate the prior probability of treatment (Compound-Disease edges) for the reasons [described here](https://git.dhimmel.com/rephetio-manuscript/#prior-probability-of-treatment). We ended up [empirically calculating](https://think-lab.github.io/d/201/#2) this probability by generating many XSwap bipartite treatment networks and seeing how often edges of a specific source-target degree combination existed ([table](https://github.com/dhimmel/learn/blob/0aae784e83cfaa00d1269f17a3bd3a6c6fdc3a0a/prior/data/degree-prior.tsv)).

@antoine-lizee had [initially proposed](https://think-lab.github.io/d/194/#2) an analytical method for computing the XSwap prior probability, but we realized it was wrong because the probabilities didn't sum the 755 (the actual number of treatment edges). In subsequent discussion, @antoine-lizee [wrote](https://doi.org/10.15363/thinklab.d201):

> To grasp the complexity of the problem, we can see that the prior probability for one particular couple Ci-Dj is not only dependent on the degrees of the two nodes Ci and Dj, but on the degrees of all the Compound and Disease nodes. As a result, it is complicated (maybe impossible) to derive an exact analytical solution

Hence, we abandoned the idea of an analytical solution to the XSwap prior, although it would be useful (not necessarily for hetmech but more generally). At this point, we have three analytical solutions:

1. **Lizee**: @antoine-lizee's [prior](https://think-lab.github.io/d/194/#2), which we know is improperly scaled. The Lizee estimate is defined as `source_degree * target_degree / (n_sources * n_targets)`
2. **Chung-Lu**: as [provided](https://github.com/greenelab/hetmech/issues/134#issuecomment-419133600) by @kkloste and not an estimate of the XSwap prior. Defined as `source_degree * target_degree / n_edges`.
3. **Kloster**: @kkloste's analytical estimate of the XSwap prior defined as `source_degree * target_degree / (n_edges) + source_degree * target_degree - source_degree - target_degree + 1`. FYI @zietzm is curious about how @kkloste derived this!

I compared all three analytic estimates to the empirical probabilities computed for Project Rephetio ([notebook](https://gist.github.com/dhimmel/44212bed10ce618da454e4508d91fac4/78afda7f7716591c52faadaff72d837a415d1e3e)). The analytic values are on the x-axis and the empirc values are on the y-axis (both values have been logit transformed):

![estimated-xswap-priors](https://user-images.githubusercontent.com/1117703/45900338-7f727700-bdad-11e8-8676-d19a21d3f1d7.png)

A perfect analytic solution would scatter around the line y = x. The scaling issue with the Lizee method is immediately apparent. The Chung-Lu estimate the prior for low degree pairs, but have issues with higher degree nodes. In fact, the formula produces values over 100% for several of the higher degree node pairs. The Kloster solution is quite good but appears to slightly underestimate the priors for higher-degree combinations.

**Comment by kkloste** [comment]
@dhimmel  Thanks for the wonderful summary.

I should have clarified that the probability I gave is asymptotic: it is the probability of a particular node pair (u,v) being connected by an edge after a sufficiently large number of iterations of xswap are applied to a given graph.

I'm attaching my analysis (see section 1.3 here:
[xswap-analysis.pdf](https://github.com/greenelab/hetmech/files/2407021/xswap-analysis.pdf)
I had originally derived the exact same formula as Lizee, but discovered a problem similar to the one you described, Daniel.
@zietzm please let me know if I can make anything in the write-up clearer. I am not 100% certain it is correct, but I cannot recognize any errors.

Whatever the cause of the discrepancy is between my formula and the observed probability, there seems to be a similar gap in the Lizee plot -- toward the top of both plots the blocks dots bend a little away from the red line. I wonder what's causing this discrepancy (apparent in Chung-Lu, too) at high degree nodes?
I don't think the number of edges or size of node degree is large enough to cause numerical issues in my formula. One possibility is that the number of iterations of xswap is not high enough for the observed to my asymptotic bound --- how many iterations of xswap were applied, @dhimmel ? I tried determining that from the notebook, but couldn't figure it out.

**Comment by dhimmel** [comment]
> how many iterations of xswap were applied

The empirical XSwap probabilities were calculated from 744,975 permuted networks ([description](https://think-lab.github.io/d/201/#2), [notebook](https://github.com/dhimmel/learn/blob/0aae784e83cfaa00d1269f17a3bd3a6c6fdc3a0a/prior/1-prior.ipynb)). For most degree-combinations, degree grouping will result in more than 744,975 observations of edge presence contributing to the empiric average. However, in general, degree grouping provides less of a sample size increase for high degree nodes (since are fewer other nodes with the same degree).

I updated the [notebook](https://gist.github.com/dhimmel/44212bed10ce618da454e4508d91fac4/629830d4d443656dc95920a4181a186f3963b6a8) (see cell 7) to show the degree pairs with the highest XSwap empiric probabilities:

compound_treats | disease_treats | xswap_prior | Chung-Lu | Kloster
-- | -- | -- | -- | --
19 | 68 | 79.6% | 171.1% | 65.9%
17 | 68 | 76.9% | 153.1% | 63.3%
15 | 68 | 73.4% | 135.1% | 60.2%
19 | 51 | 73.4% | 128.3% | 58.5%
14 | 68 | 71.5% | 126.1% | 58.5%
17 | 51 | 69.8% | 114.8% | 55.8%
13 | 68 | 69.4% | 117.1% | 56.7%
12 | 68 | 67.0% | 108.1% | 54.7%
15 | 51 | 65.9% | 101.3% | 52.6%
19 | 37 | 65.2% | 93.1% | 50.1%

Note the Chung-Lu probabilities over 100%. Not sure what to make of these, besides that Chung-Lu cannot handle these high degree pairs? The XSwap empiric and Kloster probabilities are different enough (e.g. 79.6% versus 65.9%) that I do think there is some fundamental difference between them. Not sure it's worth our time to chase it down however.

> I should have clarified that the probability I gave is asymptotic

I do think our iteration number should be sufficiently large. We could see if this discrepency occurs similarly for other edges. Let me check with @danich1 who has generated XSwap probabilities for Disease-associates-Gene edges.

**Comment by dhimmel** [comment]
I expanded the XSwap-versus-analytical plot to include the _Disease-associates-Gene_ metaedge ([notebook](https://gist.github.com/dhimmel/44212bed10ce618da454e4508d91fac4/3a4be8ec2d267cf64fc5295274b8e8a231c9b5cb)). I removed the Lizee panel, since I didn't feel it was offering anything valuable. I also removed the logit transformation:

![xswap-versus-analytic-priors](https://user-images.githubusercontent.com/1117703/45973657-17ba6700-c00d-11e8-9640-06f5d7bbed05.png)

The revised plot indicates that the Kloster method does seem to systematically underestimate probabilities for high-degree node pairs. The Chung-Lu estimate continues to produce probabilities over 100%, which makes me wonder we have the right analytical formula for this model?

**Comment by kkloste** [comment]
@dhimmel  Hm, this is strange indeed.

* the formulae could be wrong (@zietzm have you looked at the derivation I sent?)
* the number of iterations of xswap could be insufficient,
* possibly the way that xswap is implemented (maybe because of how the pseudo-random selection of edges / edge endpoints works) is skewing the sampling we're doing
* the number of iterations of xswap might not be sufficient?

Those are the possibilities I can think of. Any other ideas?

**Comment by kkloste** [comment]
I should have said earlier -- the problem with the "Chung-Lu formula" I had been aware of, and it's introduced because of the way I adapted the traditional Chung-Lu probability to guarantee that exactly $m$ edges exist.

In retrospect, the adaptation I made is incorrect --- @dhimmel if you use $d_u d_v / m^2$ instead of $d_ud_v/m$, then the values will be feasible probabilities (instead of values greater than 1).

My apology for my silly mistake.

**Comment by kkloste** [comment]
@dhimmel @zietzm I finally found a flaw in my derivation last week, and recently finished deriving and verifying a new formula that I feel pretty confident is correct. I also ran my own experiments to check correctness, and obtained pretty good correlation. Derivation attached.

The corrected formula is:
$P( u,v ) = \frac{d_u d_v}{ \binom{m}{2} - \sum_{v\inV} \binom{d_u}{2}  - m + d_u + d_v + d_ud_v - 1 } $

Note that my modified Chung-Lu formula was also incorrect, because what we're doing is fundamentally different from Chung-Lu (CL flips a coin for every potential edge, which does not guarantee that $m$ edges exist, whereas we guarantee that $m$ edges always exist. I tried accounting for this when I modified CL, but I did so incorrectly).

[xswap-analysis.pdf](https://github.com/greenelab/hetmech/files/2434363/xswap-analysis.pdf)

**Comment by dhimmel** [comment]
@kkloste super excited to try out the new formula! I played around a [bit in this notebook](https://gist.github.com/dhimmel/44212bed10ce618da454e4508d91fac4/3e12371e41d6e23007694e93a664a6f5c7cd4ef2#file-xswap-prior-ipynb) in regards to computing the number of wedges (the summation term in the denominator.

If I understand, the summation refers to going through each source node and identifying the degree. Then doing a degree-choose-2 operation, and summing this value for every source node. In other words, this wedge number is computed once from the node degree sequence of source or target nodes.

See in the notebook that doing this with source nodes and target nodes gives different values. Does that make sense? Since the rest of the formula is symmetric between source and target nodes, I'm assuming that the wedge term should be the same for source nodes and target nodes?

**Comment by kkloste** [comment]
The summation iterates over **all** vertices (not just source vertices), and for each vertex $u$ adds (degree($u$) choose 2) to the summation.

The reason why this summation gives the desired value is:
For each vertex $u$, if you pick any two neighbors $n_1, n_2$, then vertices $n_1, u, n_2$ form a wedge. Thus, every choice of 2 vertices from N(u) gives a distinct wedge. Moreover, every single wedge in the graph is accounted for in this way.

And yes, given a degree sequence you can compute this summation **one time**, and never have to re-compute it again :-)

**Comment by zietzm** [comment]
@kkloste I have been having some trouble with the latest method update. I really like the wedge element and the way that this counts things, but for some reason I have been unable to show reasonable results. When I try to apply the method to real data, the combination (m 2) term totally dominates all other terms in the denominator and all probabilities are very low. I haven't been able to identify what might be causing the error, but I hope to look more closely in the upcoming days.

This figure shows what I mean. It compares your original method with the latest update.

![image](https://user-images.githubusercontent.com/7230303/46378917-23400a80-c66b-11e8-9d68-531f2dc18da0.png)

I believe that I have a method that will work. However, it depends on the correctness of `p` and `q` as defined in the two PDFs. This method does not achieve perfection, but I think it is sound, conditional on the definitions of `p` and `q`. I hope to write it up in the next few days and post a PDF here. For now, here is a plot and the formula I used.

![image](https://user-images.githubusercontent.com/7230303/46379017-82058400-c66b-11e8-8afd-3ccb9690ceea.png)
```python
P_uv = du * dv * ((du * dv)**2 + (m - du - dv + 1)**2) ** (-0.5)
```

**Comment by kkloste** [comment]
@zietzm I ran into the same problem when I was testing my analysis, but I believe I determined the problem. The discrepancy is because the probability formula is for a single edge existing, whereas the observed frequencies that we're plotting are taken from $m$ edges.

We have thought that we were plotting "observed frequency vs analytic probability".
Instead, we should be thinking of it as "number of observed edges vs expected number of edges".

Let N be he number of graphs sampled. For each sampled graph, we see m edges. So we observe `m*N` total edges.
If we multiply the x values by `m*N` that should balance things out.

**Comment by kkloste** [comment]
`m` is the (fixed) number of edges in the graph.

I've been working on a response to your question.
Here are plots from a synthetic network I made and ran xswap on.
After generating one initial graph with a fixed number of edges, `m`, I then perform `N=1000` trials of the following:
run `xswap` 1000 times on the graph.
Record the edges present.
Repeat.

Then, the observed probability of an edge appearing is
# times the edge appeared / (`N * m`)

Plotting this against the formula yields this:

![probability-formula](https://user-images.githubusercontent.com/4999436/46551730-87024780-c8a6-11e8-8c95-e5e21ab543c8.png)

The values plotted are all between 0 and 1 (i.e. valid probabilities, unlike my erroneous modified-Chung-Lu from before),
and that the correlation seems very strong, but the scaling is for some reason off.

Re-scaling required roughly multiplying by 2, which makes me wonder if I missed a factor of 2 in the formula. (It's possible that, since each instance of xswap technically moves 2 edges instead of 1, I'm failing to account for that?).
It yields this:
![probability-formula-scaled](https://user-images.githubusercontent.com/4999436/46551867-de081c80-c8a6-11e8-9ee2-e1b76a44b379.png)


The initial graph used is only a 75-by-100 randomly generated bipartite graph.
I've done this on a handful of smallish graphs (50-by-75, 100-by-125) with the same results.
(The same very strong linear correlation between the probability formula and observation.)

One thing I can't explain -- the scaling factor (which was 2 for this graph) seems to change a bit with the number of xswaps used. The relationship between the two quantities always appears to be very strongly linear, which suggests the meat of the formula is correct.

But the fact that the scaling varies perplexes me.

**Comment by kkloste** [comment]
I may have found a bug in my code that will explain the variation in the scaling coefficient.
It looks like it might just be a factor of 2 (and the variation was caused by a bug).
Will report back once I've run more experiments with the corrected code.

**Comment by kkloste** [comment]
Ok, confirming that with the bug corrected, all experiments yield data where a factor of 2 corrects the scaling problem.

More specifically, it looks like I was missing a factor of `(1/2)` from the probability formula,
and this corrected formula is behaving well now across all experiments.

![probability-formula-n1000-s1000](https://user-images.githubusercontent.com/4999436/46554426-2f67da00-c8ae-11e8-92d9-8fb28f63a4ac.png)

**Comment by kkloste** [comment]
By the way, the black dots represent edges that were present in the initial graph; the red dots are edges from all other graphs.
It is an obsolete feature left over from when I was checking there was no obvious bias from the input graph.

**Comment by zietzm** [comment]
@kkloste Using your definitions of `p` and `q`, I get the following probability of an edge:
![image](https://user-images.githubusercontent.com/7230303/46685695-1324af80-cbc4-11e8-9d2e-14350463e358.png)
See the derivation here -> [xswap.pdf](https://github.com/greenelab/hetmech/files/2461690/Hetmech_math.2.pdf). 

I have been working with your formula, but am having trouble getting well-fitting results. To clarify, is your method accurately summed-up by the following: (from above PDF)

![image](https://user-images.githubusercontent.com/7230303/46690095-7ec04a00-cbcf-11e8-87dc-018934b4e486.png)

If so, scaling by `m` for easier comparison with my method and your previous method, I get the following plot, showing your original method, your updated method (scaled), and the method I describe in the PDF.

![image](https://user-images.githubusercontent.com/7230303/46690215-baf3aa80-cbcf-11e8-87da-6592d2caa157.png)

**Comment by kkloste** [comment]
@zietzm Thanks for writing that up. I glanced at it, and it seems interesting, but I'm preoccupied with a deadline this week and will have to wait until next week to respond thoughtfully.

To answer your question, I'm not 100% sure your explanation of my method is quite right;
I _think_ it is, but just to be totally clear:
the quantity `N` for me is not the number of **permutations**, but the number of distinct graphs (where each graph is produced by performing a certain number of xswap permutations on an initial graph).
I think that's what you meant, but just double checking for clarity.
That detail aside, your description (as I understand it) matches my method.

Some thoughts:

"Old Kloster" should be omitted entirely, it's definitely very incorrect (despite the nice correlation is somehow has).

There seems to be something going on near x=0.5 in the plot for both of us -- a kind of inflection point? And that might have something to do with the quantity $d_u d_v$ getting very large? Which would only happen if there are very large degrees in the graph; which is more likely to happen if there are a whole lot of edges in the graph --- It's possible that the plots I showed (where my formula had a clear linear relationship with observation) were for graphs with such low edge density that the terms $d_u d_v$ never got large enough for me to notice the problem.

Can you tell me what the edge density is in the graph(s) you're testing on, @zietzm ?

**Comment by zietzm** [comment]
In an example graph for DpS:

![image](https://user-images.githubusercontent.com/7230303/46694738-a2898d00-cbdb-11e8-82df-1de17f5b7231.png)

There are 3357 edges, with 137 source nodes and 438 target nodes. Here is a distribution of degrees.

![image](https://user-images.githubusercontent.com/7230303/46694775-b503c680-cbdb-11e8-96dd-6496d59cab4b.png)

**Comment by kkloste** [comment]
Thanks for that info, @zietzm .
The edge density looks to be about 0.065 on these graphs.
In contrast, the graphs I worked on had edge densities 0.1 and 0.2,
so my "higher edge density" theory doesn't quite explain it.

Hm, what are the dots near y=0 in these plots?
