### ISSUE TITLE
DWPC implementation coverage of the Project Rephetio metapaths 

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#47]
We currently have implemented the DWPC (see #45) for certain metapaths. The question is, of the 1,206 metapaths in Project Rephetio, how many will our current implementation succeed on?

You can get the metapath info [here](https://github.com/dhimmel/learn/blob/25093893ed53730ab5cfdac49561c4b6bd3376c5/all-features/data/metapaths.json) or [here](https://github.com/dhimmel/learn/blob/25093893ed53730ab5cfdac49561c4b6bd3376c5/prediction/features/metapaths.tsv). An interactive metapath browser for Project Rephetio is also available at http://het.io/repurpose/metapaths.html

**Comment by zietzm** [comment]
**454 / 1206** metapaths will throw an error when running `dwpc`. This error stems from `get_segments` in which an error is raised if there are overlapping segments of duplicate metanodes.

I am currently running the full `dwpc` function for all the 752 metapaths between all compounds and diseases that will run in our current implementation. From this, I hope to compare predictions to Rephetio's predictions, at least for this subset of metapaths. I think it would be really interesting to see where the metapaths we don't support fall in the ranking of metapaths by AUROC and coef. It may be useful to know if the paths we don't support with hetmech are informative or not.

**Comment by dhimmel** [comment]
> 454 / 1206 metapaths will throw an error when running dwpc

@zietzm can you submit a pull request with this notebook?

**Comment by zietzm** [comment]
Sure thing! It is running something at the moment, but I will pull request as soon as it is complete.

**Comment by kkloste** [comment]
I've made some progress this week on the "two repeated metanodes, interleaved" case this week.
Specifically the "ABAB" sub-case ("BAAB" requires a different solution, I believe).
Hopefully this will bring down that "454" to a lower number.

**Comment by zietzm** [comment]
![adjacency_matrix_size](https://user-images.githubusercontent.com/7230303/27748841-f833d398-5d9e-11e7-9680-094648b0f9f4.png)

I wanted to reference the relative sizes here, so I put the table in above. I will hopefully have one soon that will show the time of multiplication for all of the relevant metaedge combinations.

**Comment by zietzm** [comment]
Another random note:
Within the [auto_convert function](https://github.com/greenelab/hetmech/blob/master/hetmech/matrix.py#L105), it may be best to add `and not sparse.issparse(matrix)`, as this reduces `dwpc` runtime using sparse matrices by about 16 percent. It looks like there is some automatic conversion being done somewhere in the function that converts csc to csr. This was the biggest time use in `dwpc` when running with a `sparse_threshold=1` or only using sparse matrices.

**Comment by zietzm** [comment]
In comparing the Rephetio DWPC results with hetmech's results, I discovered that there is disagreement between the methods for about 13.4 percent of the metapaths. I haven't been able to trace this error back to a source error. However, I was using an example path with specific nodes and edges, that I think could help our arrival at a solution. 

I was looking at the path 'CrCrCrCtD', as suggested by the hetnet folks at Scripps. I noticed a point of disagreement between the nodes "DB00352" and "DOID:2531". I loaded a Neo4j instance and by hand saw that there should not be a 'CrCrCrCtD' path between them. Rephetio correctly gave a path count of 0 for this instance. Hetmech returned 1. 

Here is the graph:
![neo0](https://user-images.githubusercontent.com/7230303/28090291-d5f0c44e-6659-11e7-94c4-ed59aa8c74ea.png)

My hypothesis is that traversal is somehow going through metanodes CCCCD by going through nodes abcbd. I am not sure about this analysis, but I think that because we stayed within the same metanode and the segments created were therefore `CrCrCrC` and `CtD`, we still used a walk count within CrCrCrC, as there is no method within the code to be sure that the same node of the same metanode within a segment is not repeated.

Another example that I think potentially strengthens this hypothesis is that another PC=0 prediction from Rephetio is in the graph below. On this one, hetmech scored PC=2. I think the one-edge difference in the scheme of the below graph and the above graph fits the picture I have.

![neo4j-1](https://user-images.githubusercontent.com/7230303/28090535-a561b5bc-665a-11e7-874f-f5db565d3afa.png)

I'm not sure where this leaves us. @kkloste, is there a potential solution for this since we appear to be dealing with nodes instead of metanodes? Perhaps we could do something like a series of subsegmentations for a repeated metanode sequence?

**Comment by dhimmel** [comment]
See the following:

- [Vagelos Report Summer 2017](https://doi.org/10.6084/m9.figshare.5346577.v1)
- [`5.rephetio-paths.ipynb`](https://github.com/greenelab/hetmech/blob/9dfb75a0920ae0240acb6efabdd806d240d265de/5.rephetio-paths.ipynb)
- [`6.compare-rephetio.ipynb`](https://github.com/greenelab/hetmech/blob/9dfb75a0920ae0240acb6efabdd806d240d265de/6.compare-rephetio.ipynb)
- [`7.rephetio-times.ipynb`](https://github.com/greenelab/hetmech/blob/9dfb75a0920ae0240acb6efabdd806d240d265de/7.rephetio-times.ipynb)

Here's the breakdown of how rephetio metapaths were classified for path counting:

```
short_repeat    599
BABA            278
BAAB            144
disjoint        131
other            32
no_repeats       18
long_repeat       4
```
